backend:
  name: github
  repo: StanisicS/palm-beach-transport

media_folder: src/posts

collections:
  - name: load-board
    label: Load Board
    folder: src/posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }
      - { name: title, label: Title }
      - { label: Image, : image, widget: image }
