backend:
  name: github
  repo: StanisicS/palm-beach-transport

media_folder: static/assets

collections:
  - name: load-board
    label: Load Board
    folder: src/pages
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
